---
- name: Installing tomcat8 role
  apt: 
   name: "{{item.a}}"
   state: "{{item.b}}"
   update_cache: "{{item.c}}"
  with_items:
   - {a: "{{pkg1}}", b: "{{state1}}", c: "{{cache1}}"}
   - {a: "{{pkg2}}", b: "{{state1}}", c: "{{cache2}}"}

  





...
