---
- name: install docker
  hosts: all
  tasks: 
   - name: install python-pip
     apt: 
      name: python-pip
      state: present
   - name: download and install docker and docker-py commands using shell cmd
     shell: "{{item}}"
     with_items: 
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip install docker-py






...
