---
- name: Implementing when conditions 
  hosts: all
  vars:
   - a: 10
  tasks:
   - name: installing httpd 
     apt:
      name: maven
      state: absent
      update_cache: yes
     when: 
      a == 20







...
