---
- name: Handlers implementing in apache2
  hosts: all
  tasks:
   - name: Installing iapache2 
     apt: 
      name: apache2
      state: present
     notify:
      - check url response
   - name: Edit the index.html page file
     copy:
      content: "HAI THIS IS SREEKANTH\n"
      dest: /var/www/html/index.html
     notify: 
      - restart apache2
  handlers:
   - name: restart apache2
     service: 
      name: apache2
      state: restarted
   - name: check url response
     uri: 
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.88.191
      - http://172.31.80.165

      












...
