---
- name: ansible playbook for downloading docker-images
  hosts: all
  tasks: 
   - name: downloading the images from dockerhub using ansible
     docker_image: 
      name: "{{item}}"
      pull: yes
     with_items: 
      - ubuntu
      - alpine
      - maven
      - registry
      - httpd










...
